// packages
import Head from 'next/head';

const SEO = () => {
	return (
		<Head>
			<meta charSet="utf-8" />
			<meta name="theme-color" content="#ffffff" />
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1.0"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default SEO;
