import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import css from 'styles/Home.module.css';

export default function Home() {
	return (
		<div className={css.container}>
			<Head>
				<title>Next.js Firebase Auth Template</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={css.main}>
				<Link href="/signup" passHref>
					<button className={css.button}>
						Go To Sign Up Page →{' '}
					</button>
				</Link>
			</main>
			<footer className={css.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={css.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
